version: '3.8'

services:
  mosquitto:
    image: eclipse-mosquitto:latest
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log

  fastapi_app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    volumes:
      - ../src:/app
    ports:
      - "8000:8000"
    depends_on:
      - mosquitto
